/*
 * module_schedules.c
 *
 *  Created on: Jan 27, 2022
 *      Author: hakan.keskin
 */

#include "include/apex/module_schedules.h"

void SET_MODULE_SCHEDULE (SCHEDULE_ID_TYPE SCHEDULE_ID,
		RETURN_CODE_TYPE *RETURN_CODE)
{
	*RETURN_CODE = NOT_AVAILABLE;
}

void GET_MODULE_SCHEDULE_STATUS (SCHEDULE_STATUS_TYPE *SCHEDULE_STATUS,
		RETURN_CODE_TYPE *RETURN_CODE)
{
	*RETURN_CODE = NOT_AVAILABLE;
}

void GET_MODULE_SCHEDULE_ID (SCHEDULE_NAME_TYPE SCHEDULE_NAME,
		SCHEDULE_ID_TYPE *SCHEDULE_ID,
		RETURN_CODE_TYPE *RETURN_CODE)
{
	*RETURN_CODE = NOT_AVAILABLE;
}
