/*
 * sp_extentions.c
 *
 *  Created on: Jan 27, 2022
 *      Author: hakan.keskin
 */

#include "include/apex/sp_extentions.h"

void READ_UPDATED_SAMPLING_MESSAGE (SAMPLING_PORT_ID_TYPE SAMPLING_PORT_ID,
		MESSAGE_ADDR_TYPE MESSAGE_ADDR,
		MESSAGE_SIZE_TYPE *LENGTH,
		UPDATED_TYPE *UPDATED,
		RETURN_CODE_TYPE *RETURN_CODE)
{
	*RETURN_CODE = NOT_AVAILABLE;
}

void GET_SAMPLING_PORT_CURRENT_STATUS (SAMPLING_PORT_ID_TYPE SAMPLING_PORT_ID,
		SAMPLING_PORT_CURRENT_STATUS_TYPE *SAMPLING_PORT_CURRENT_STATUS,
		RETURN_CODE_TYPE *RETURN_CODE)
{
	*RETURN_CODE = NOT_AVAILABLE;
}

void READ_SAMPLING_MESSAGE_CONDITIONAL (SAMPLING_PORT_ID_TYPE SAMPLING_PORT_ID,
		SYSTEM_TIME_TYPE REF_TIME_STAMP,
		MESSAGE_ADDR_TYPE MESSAGE_ADDR,
		MESSAGE_SIZE_TYPE *LENGTH,
		SYSTEM_TIME_TYPE *TIME_STAMP,
		RETURN_CODE_TYPE *RETURN_CODE)
{
	*RETURN_CODE = NOT_AVAILABLE;
}
