/*
 * name_sarvice.c
 *
 *  Created on: Jan 27, 2022
 *      Author: hakan.keskin
 */

#include "include/apex/name_sarvice.h"

void CREATE_NAME_SERVICE (NAME_SERVICE_NAME_TYPE NAME_SERVICE_NAME,
		QUEUING_DISCIPLINE_TYPE QUEUING_DISCIPLINE,
		NAME_SERVICE_ID_TYPE *SERVICE_ID,
		RETURN_CODE_TYPE *RETURN_CODE )
{
	*RETURN_CODE = NOT_AVAILABLE;
}

void GET_NAME (NAME_SERVICE_ID_TYPE SERVICE_ID,
		SAP_ADDRESS_TYPE SAP_ADDRESS,
		SYSTEM_TIME_TYPE TIME_OUT,
		NAME_SERVICE_ADDR_TYPE NAME_ADDR,
		NAME_SERVICE_LENGTH_TYPE IN_NAME_LENGTH,
		NAME_SERVICE_LENGTH_TYPE *OUT_NAME_LENGTH,
		RETURN_CODE_TYPE *RETURN_CODE )
{
	*RETURN_CODE = NOT_AVAILABLE;
}

void GET_ADDRESS (NAME_SERVICE_ID_TYPE SERVICE_ID,
		NAME_SERVICE_ADDR_TYPE NAME,
		NAME_SERVICE_LENGTH_TYPE *NAME_LENGTH,
		SYSTEM_TIME_TYPE TIME_OUT,
		SAP_ADDRESS_TYPE *SAP_ADDRESS,
		RETURN_CODE_TYPE *RETURN_CODE )
{
	*RETURN_CODE = NOT_AVAILABLE;
}
