/*
 * queuing.c
 *
 *  Created on: Jan 27, 2022
 *      Author: hakan.keskin
 */

#include "include/apex/queuing.h"

void CREATE_QUEUING_PORT (QUEUING_PORT_NAME_TYPE QUEUING_PORT_NAME,
		MESSAGE_SIZE_TYPE MAX_MESSAGE_SIZE,
		MESSAGE_RANGE_TYPE MAX_NB_MESSAGE,
		PORT_DIRECTION_TYPE PORT_DIRECTION,
		QUEUING_DISCIPLINE_TYPE QUEUING_DISCIPLINE,
		QUEUING_PORT_ID_TYPE *QUEUING_PORT_ID,
		RETURN_CODE_TYPE *RETURN_CODE )
{
	*RETURN_CODE = NOT_AVAILABLE;
}

void SEND_QUEUING_MESSAGE (QUEUING_PORT_ID_TYPE QUEUING_PORT_ID,
		MESSAGE_ADDR_TYPE MESSAGE_ADDR,
		MESSAGE_SIZE_TYPE LENGTH,
		SYSTEM_TIME_TYPE TIME_OUT,
		RETURN_CODE_TYPE *RETURN_CODE)
{
	*RETURN_CODE = NOT_AVAILABLE;
}

void RECEIVE_QUEUING_MESSAGE (QUEUING_PORT_ID_TYPE QUEUING_PORT_ID,
		SYSTEM_TIME_TYPE TIME_OUT,
		MESSAGE_ADDR_TYPE MESSAGE_ADDR,
		MESSAGE_SIZE_TYPE *LENGTH,
		RETURN_CODE_TYPE *RETURN_CODE )
{
	*RETURN_CODE = NOT_AVAILABLE;
}

void GET_QUEUING_PORT_STATUS (QUEUING_PORT_ID_TYPE QUEUING_PORT_ID,
		QUEUING_PORT_STATUS_TYPE *QUEUING_PORT_STATUS,
		RETURN_CODE_TYPE *RETURN_CODE )
{
	*RETURN_CODE = NOT_AVAILABLE;
}

void CLEAR_QUEUING_PORT (QUEUING_PORT_ID_TYPE QUEUING_PORT_ID,
		RETURN_CODE_TYPE *RETURN_CODE )
{
	*RETURN_CODE = NOT_AVAILABLE;
}
