/*
 * process.c
 *
 *  Created on: Jan 27, 2022
 *      Author: hakan.keskin
 */


#include "include/apex/process.h"

void CREATE_PROCESS (PROCESS_ATTRIBUTE_TYPE *ATTRIBUTES,
		PROCESS_ID_TYPE *PROCESS_ID,
		RETURN_CODE_TYPE *RETURN_CODE )
{
	*RETURN_CODE = NOT_AVAILABLE;
}

void SET_PRIORITY(PROCESS_ID_TYPE PROCESS_ID,
	PRIORITY_TYPE PRIORITY,
	RETURN_CODE_TYPE *RETURN_CODE)
{
	*RETURN_CODE = NOT_AVAILABLE;
}

void SUSPEND_SELF(SYSTEM_TIME_TYPE TIME_OUT,
	RETURN_CODE_TYPE *RETURN_CODE)
{
	*RETURN_CODE = NOT_AVAILABLE;
}

void SUSPEND(PROCESS_ID_TYPE PROCESS_ID,
	RETURN_CODE_TYPE *RETURN_CODE)
{
	*RETURN_CODE = NOT_AVAILABLE;
}

void RESUME(PROCESS_ID_TYPE PROCESS_ID,
	RETURN_CODE_TYPE *RETURN_CODE)
{
	*RETURN_CODE = NOT_AVAILABLE;
}

void STOP_SELF(void)
{

}

void STOP(PROCESS_ID_TYPE PROCESS_ID,
	RETURN_CODE_TYPE *RETURN_CODE)
{
	*RETURN_CODE = NOT_AVAILABLE;

}

void START (PROCESS_ID_TYPE PROCESS_ID,
		RETURN_CODE_TYPE *RETURN_CODE )
{
	*RETURN_CODE = NOT_AVAILABLE;
}

void DELAYED_START(PROCESS_ID_TYPE PROCESS_ID,
	SYSTEM_TIME_TYPE DELAY_TIME,
	RETURN_CODE_TYPE *RETURN_CODE)
{
	*RETURN_CODE = NOT_AVAILABLE;
}

void LOCK_PREEMPTION(LOCK_LEVEL_TYPE *LOCK_LEVEL,
	RETURN_CODE_TYPE *RETURN_CODE)
{
	*RETURN_CODE = NOT_AVAILABLE;
}

void UNLOCK_PREEMPTION(LOCK_LEVEL_TYPE *LOCK_LEVEL,
	RETURN_CODE_TYPE *RETURN_CODE)
{
	*RETURN_CODE = NOT_AVAILABLE;
}

void GET_MY_ID(PROCESS_ID_TYPE *PROCESS_ID,
	RETURN_CODE_TYPE *RETURN_CODE)
{
	*RETURN_CODE = NOT_AVAILABLE;
}

void GET_PROCESS_ID(PROCESS_NAME_TYPE PROCESS_NAME,
	PROCESS_ID_TYPE *PROCESS_ID,
	RETURN_CODE_TYPE *RETURN_CODE)
{
	*RETURN_CODE = NOT_AVAILABLE;
}

void GET_PROCESS_STATUS(PROCESS_ID_TYPE PROCESS_ID,
	PROCESS_STATUS_TYPE *PROCESS_STATUS,
	RETURN_CODE_TYPE *RETURN_CODE)
{





	*RETURN_CODE = NOT_AVAILABLE;

}
