/*
 * file_system.c
 *
 *  Created on: Jan 27, 2022
 *      Author: hakan.keskin
 */

#include "include/apex/file_system.h"

void OPEN_NEW_FILE (FILE_NAME_TYPE FILE_NAME,
		FILE_ID_TYPE *FILE_ID,
		RETURN_CODE_TYPE *RETURN_CODE,
		FILE_ERRNO_TYPE *ERRNO )
{
	*RETURN_CODE = NOT_AVAILABLE;
}

void OPEN_FILE (FILE_NAME_TYPE FILE_NAME,
		FILE_MODE_TYPE FILE_MODE,
		FILE_ID_TYPE *FILE_ID,
		RETURN_CODE_TYPE *RETURN_CODE,
		FILE_ERRNO_TYPE *ERRNO )
{
	*RETURN_CODE = NOT_AVAILABLE;
}

void CLOSE_FILE (FILE_ID_TYPE FILE_ID,
		RETURN_CODE_TYPE *RETURN_CODE,
		FILE_ERRNO_TYPE *ERRNO )
{
	*RETURN_CODE = NOT_AVAILABLE;
}

void READ_FILE (FILE_ID_TYPE FILE_ID,
		MESSAGE_ADDR_TYPE MESSAGE_ADDR,
		MESSAGE_SIZE_TYPE IN_LENGTH,
		MESSAGE_SIZE_TYPE *OUT_LENGTH,
		RETURN_CODE_TYPE *RETURN_CODE,
		FILE_ERRNO_TYPE *ERRNO )
{
	*RETURN_CODE = NOT_AVAILABLE;
}

void WRITE_FILE (FILE_ID_TYPE FILE_ID,
		MESSAGE_ADDR_TYPE MESSAGE_ADDR,
		MESSAGE_SIZE_TYPE LENGTH,
		RETURN_CODE_TYPE *RETURN_CODE,
		FILE_ERRNO_TYPE *ERRNO )
{
	*RETURN_CODE = NOT_AVAILABLE;
}

void SEEK_FILE (FILE_ID_TYPE FILE_ID,
		FILE_SIZE_TYPE OFFSET,
		FILE_SEEK_TYPE WHENCE,
		FILE_SIZE_TYPE *POSITION,
		RETURN_CODE_TYPE *RETURN_CODE,
		FILE_ERRNO_TYPE *ERRNO )
{
	*RETURN_CODE = NOT_AVAILABLE;
}

void RESIZE_FILE (FILE_ID_TYPE FILE_ID,
		FILE_SIZE_TYPE NEW_SIZE,
		RETURN_CODE_TYPE *RETURN_CODE,
		FILE_ERRNO_TYPE *ERRNO )
{
	*RETURN_CODE = NOT_AVAILABLE;
}

void SYNC_FILE (FILE_ID_TYPE FILE_ID,
		RETURN_CODE_TYPE *RETURN_CODE,
		FILE_ERRNO_TYPE *ERRNO )
{
	*RETURN_CODE = NOT_AVAILABLE;
}

void REMOVE_FILE (FILE_NAME_TYPE FILE_NAME,
		RETURN_CODE_TYPE *RETURN_CODE,
		FILE_ERRNO_TYPE *ERRNO )
{
	*RETURN_CODE = NOT_AVAILABLE;
}

void RENAME_FILE (FILE_NAME_TYPE OLD_FILE_NAME,
		FILE_NAME_TYPE NEW_FILE_NAME,
		RETURN_CODE_TYPE *RETURN_CODE,
		FILE_ERRNO_TYPE *ERRNO )
{
	*RETURN_CODE = NOT_AVAILABLE;
}

void GET_FILE_STATUS (FILE_ID_TYPE FILE_ID,
		FILE_STATUS_TYPE *FILE_STATUS,
		RETURN_CODE_TYPE *RETURN_CODE,
		FILE_ERRNO_TYPE *ERRNO )
{
	*RETURN_CODE = NOT_AVAILABLE;
}

void GET_VOLUME_STATUS (FILE_NAME_TYPE FILE_NAME,
		VOLUME_STATUS_TYPE *VOLUME_STATUS,
		RETURN_CODE_TYPE *RETURN_CODE,
		FILE_ERRNO_TYPE *ERRNO )
{
	*RETURN_CODE = NOT_AVAILABLE;
}

void OPEN_DIRECTORY (FILE_NAME_TYPE DIRECTORY_NAME,
		DIRECTORY_ID_TYPE *DIRECTORY_ID,
		RETURN_CODE_TYPE *RETURN_CODE,
		FILE_ERRNO_TYPE *ERRNO )
{
	*RETURN_CODE = NOT_AVAILABLE;
}

void CLOSE_DIRECTORY (DIRECTORY_ID_TYPE DIRECTORY_ID,
		RETURN_CODE_TYPE *RETURN_CODE,
		FILE_ERRNO_TYPE *ERRNO )
{
	*RETURN_CODE = NOT_AVAILABLE;
}

void READ_DIRECTORY (DIRECTORY_ID_TYPE DIRECTORY_ID,
		DIRECTORY_ENTRY_TYPE *ENTRY_NAME,
		ENTRY_KIND_TYPE *ENTRY_KIND,
		RETURN_CODE_TYPE *RETURN_CODE,
		FILE_ERRNO_TYPE *ERRNO )
{
	*RETURN_CODE = NOT_AVAILABLE;
}

void REWIND_DIRECTORY (DIRECTORY_ID_TYPE DIRECTORY_ID,
		RETURN_CODE_TYPE *RETURN_CODE,
		FILE_ERRNO_TYPE *ERRNO )
{
	*RETURN_CODE = NOT_AVAILABLE;
}

void MAKE_DIRECTORY (FILE_NAME_TYPE DIRECTORY_NAME,
		RETURN_CODE_TYPE *RETURN_CODE,
		FILE_ERRNO_TYPE *ERRNO )
{
	*RETURN_CODE = NOT_AVAILABLE;
}

void REMOVE_DIRECTORY (FILE_NAME_TYPE DIRECTORY_NAME,
		RETURN_CODE_TYPE *RETURN_CODE,
		FILE_ERRNO_TYPE *ERRNO )
{
	*RETURN_CODE = NOT_AVAILABLE;
}

void SYNC_DIRECTORY (DIRECTORY_ID_TYPE DIRECTORY_ID,
		RETURN_CODE_TYPE *RETURN_CODE,
		FILE_ERRNO_TYPE *ERRNO )
{
	*RETURN_CODE = NOT_AVAILABLE;
}

void RENAME_DIRECTORY (FILE_NAME_TYPE OLD_DIRECTORY_NAME,
		FILE_NAME_TYPE NEW_DIRECTORY_NAME,
		RETURN_CODE_TYPE *RETURN_CODE,
		FILE_ERRNO_TYPE *ERRNO )
{
	*RETURN_CODE = NOT_AVAILABLE;
}
