/*
 * blackboard.c
 *
 *  Created on: Jan 27, 2022
 *      Author: hakan.keskin
 */

#include "include/apex/blackboard.h"

void CREATE_BLACKBOARD(BLACKBOARD_NAME_TYPE BLACKBOARD_NAME,
		MESSAGE_SIZE_TYPE MAX_MESSAGE_SIZE,
		BLACKBOARD_ID_TYPE *BLACKBOARD_ID,
		RETURN_CODE_TYPE *RETURN_CODE)
{
	*RETURN_CODE = NOT_AVAILABLE;
}

void DISPLAY_BLACKBOARD(BLACKBOARD_ID_TYPE BLACKBOARD_ID,
		MESSAGE_ADDR_TYPE MESSAGE_ADDR,
		MESSAGE_SIZE_TYPE LENGTH,
		RETURN_CODE_TYPE *RETURN_CODE )
{
	*RETURN_CODE = NOT_AVAILABLE;
}

void READ_BLACKBOARD(BLACKBOARD_ID_TYPE BLACKBOARD_ID,
		SYSTEM_TIME_TYPE TIME_OUT,
		MESSAGE_ADDR_TYPE MESSAGE_ADDR,
		MESSAGE_SIZE_TYPE *LENGTH,
		RETURN_CODE_TYPE *RETURN_CODE )
{
	*RETURN_CODE = NOT_AVAILABLE;
}

void CLEAR_BLACKBOARD(BLACKBOARD_ID_TYPE BLACKBOARD_ID,
		RETURN_CODE_TYPE *RETURN_CODE )
{
	*RETURN_CODE = NOT_AVAILABLE;
}

void GET_BLACKBOARD_ID (BLACKBOARD_NAME_TYPE BLACKBOARD_NAME,
		BLACKBOARD_ID_TYPE *BLACKBOARD_ID,
		RETURN_CODE_TYPE *RETURN_CODE )
{
	*RETURN_CODE = NOT_AVAILABLE;
}

void GET_BLACKBOARD_STATUS (BLACKBOARD_ID_TYPE BLACKBOARD_ID,
		BLACKBOARD_STATUS_TYPE *BLACKBOARD_STATUS,
		RETURN_CODE_TYPE *RETURN_CODE )
{
	*RETURN_CODE = NOT_AVAILABLE;
}
