/*
 * sampling.c
 *
 *  Created on: Jan 27, 2022
 *      Author: hakan.keskin
 */

#include "include/apex/sampling.h"

void CREATE_SAMPLING_PORT (SAMPLING_PORT_NAME_TYPE SAMPLING_PORT_NAME,
		MESSAGE_SIZE_TYPE MAX_MESSAGE_SIZE,
		PORT_DIRECTION_TYPE PORT_DIRECTION,
		SYSTEM_TIME_TYPE REFRESH_PERIOD,
		SAMPLING_PORT_ID_TYPE *SAMPLING_PORT_ID,
		RETURN_CODE_TYPE *RETURN_CODE )
{
	*RETURN_CODE = NOT_AVAILABLE;
}

void WRITE_SAMPLING_MESSAGE (SAMPLING_PORT_ID_TYPE SAMPLING_PORT_ID,
		MESSAGE_ADDR_TYPE MESSAGE_ADDR,
		MESSAGE_SIZE_TYPE LENGTH,
		RETURN_CODE_TYPE *RETURN_CODE )
{
	*RETURN_CODE = NOT_AVAILABLE;
}

void READ_SAMPLING_MESSAGE (SAMPLING_PORT_ID_TYPE SAMPLING_PORT_ID,
		MESSAGE_ADDR_TYPE MESSAGE_ADDR,
		MESSAGE_SIZE_TYPE *LENGTH,
		VALIDITY_TYPE *VALIDITY,
		RETURN_CODE_TYPE *RETURN_CODE )
{
	*RETURN_CODE = NOT_AVAILABLE;
}
