/*
 * logbook.c
 *
 *  Created on: Jan 27, 2022
 *      Author: hakan.keskin
 */

#include "include/apex/logbook.h"

void CREATE_LOGBOOK (LOGBOOK_NAME_TYPE LOGBOOK_NAME,
		MESSAGE_SIZE_TYPE MAX_MESSAGE_SIZE,
		MESSAGE_RANGE_TYPE MAX_NB_LOGGED_MESSAGES,
		MESSAGE_RANGE_TYPE MAX_NB_IN_PROGRESS_MESSAGES,
		LOGBOOK_ID_TYPE *LOGBOOK_ID,
		RETURN_CODE_TYPE *RETURN_CODE)
{
	*RETURN_CODE = NOT_AVAILABLE;
}

void WRITE_LOGBOOK (LOGBOOK_ID_TYPE LOGBOOK_ID,
		MESSAGE_ADDR_TYPE MESSAGE_ADDR,
		MESSAGE_SIZE_TYPE LENGTH,
		RETURN_CODE_TYPE *RETURN_CODE)
{
	*RETURN_CODE = NOT_AVAILABLE;
}

void OVERWRITE_LOGBOOK (LOGBOOK_ID_TYPE LOGBOOK_ID,
		MESSAGE_ADDR_TYPE MESSAGE_ADDR,
		MESSAGE_SIZE_TYPE LENGTH,
		RETURN_CODE_TYPE *RETURN_CODE)
{
	*RETURN_CODE = NOT_AVAILABLE;
}

void READ_LOGBOOK (LOGBOOK_ID_TYPE LOGBOOK_ID,
		MESSAGE_RANGE_TYPE LOGBOOK_ENTRY,
		MESSAGE_ADDR_TYPE MESSAGE_ADDR,
		MESSAGE_SIZE_TYPE *LENGTH,
		WRITE_STATUS_TYPE *WRITE_STATUS,
		RETURN_CODE_TYPE *RETURN_CODE)
{
	*RETURN_CODE = NOT_AVAILABLE;
}

void CLEAR_LOGBOOK (LOGBOOK_ID_TYPE LOGBOOK_ID,
		RETURN_CODE_TYPE *RETURN_CODE)
{
	*RETURN_CODE = NOT_AVAILABLE;
}

void GET_LOGBOOK_ID (LOGBOOK_NAME_TYPE LOGBOOK_NAME,
		LOGBOOK_ID_TYPE *LOGBOOK_ID,
		RETURN_CODE_TYPE *RETURN_CODE)
{
	*RETURN_CODE = NOT_AVAILABLE;
}

void GET_LOGBOOK_STATUS (LOGBOOK_ID_TYPE LOGBOOK_ID,
		LOGBOOK_STATUS_TYPE *LOGBOOK_STATUS,
		RETURN_CODE_TYPE *RETURN_CODE)
{
	*RETURN_CODE = NOT_AVAILABLE;
}
