/*
 * error.c
 *
 *  Created on: Jan 27, 2022
 *      Author: hakan.keskin
 */

#include "include/apex/error.h"

void REPORT_APPLICATION_MESSAGE (MESSAGE_ADDR_TYPE MESSAGE_ADDR,
		MESSAGE_SIZE_TYPE LENGTH,
		RETURN_CODE_TYPE *RETURN_CODE )
{
	*RETURN_CODE = NOT_AVAILABLE;
}

void CREATE_ERROR_HANDLER (SYSTEM_ADDRESS_TYPE ENTRY_POINT,
		STACK_SIZE_TYPE STACK_SIZE,
		RETURN_CODE_TYPE *RETURN_CODE )
{
	*RETURN_CODE = NOT_AVAILABLE;
}

void GET_ERROR_STATUS (ERROR_STATUS_TYPE *ERROR_STATUS,
		RETURN_CODE_TYPE *RETURN_CODE )
{
	*RETURN_CODE = NOT_AVAILABLE;
}

void RAISE_APPLICATION_ERROR (ERROR_CODE_TYPE ERROR_CODE,
		MESSAGE_ADDR_TYPE MESSAGE_ADDR,
		ERROR_MESSAGE_SIZE_TYPE LENGTH,
		RETURN_CODE_TYPE *RETURN_CODE )
{
	*RETURN_CODE = NOT_AVAILABLE;
}
